<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'GuzzleHttp\\Stream\\' => array($vendorDir . '/guzzlehttp/streams/src'),
    'GuzzleHttp\\Ring\\' => array($vendorDir . '/guzzlehttp/ringphp/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'CommerceGuys\\Guzzle\\Oauth2\\' => array($vendorDir . '/commerceguys/guzzle-oauth2-plugin/src'),
    'BoletoSimples\\' => array($vendorDir . '/boletosimples/boletosimples/src/BoletoSimples', $vendorDir . '/boletosimples/boletosimples/src/BoletoSimples/Resources'),
);
