<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit82ae54f036baa84772f44e235d3aa36c
{
    public static $files = array (
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        '0898c717d53a99d283b47fb2e4f40ba9' => __DIR__ . '/..' . '/boletosimples/boletosimples/src/BoletoSimples.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'React\\Promise\\' => 14,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Ring\\' => 16,
            'GuzzleHttp\\' => 11,
        ),
        'C' => 
        array (
            'CommerceGuys\\Guzzle\\Oauth2\\' => 27,
        ),
        'B' => 
        array (
            'BoletoSimples\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Ring\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/ringphp/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'CommerceGuys\\Guzzle\\Oauth2\\' => 
        array (
            0 => __DIR__ . '/..' . '/commerceguys/guzzle-oauth2-plugin/src',
        ),
        'BoletoSimples\\' => 
        array (
            0 => __DIR__ . '/..' . '/boletosimples/boletosimples/src/BoletoSimples',
            1 => __DIR__ . '/..' . '/boletosimples/boletosimples/src/BoletoSimples/Resources',
        ),
    );

    public static $classMap = array (
        'BeforeValidException' => __DIR__ . '/..' . '/firebase/php-jwt/Exceptions/BeforeValidException.php',
        'ExpiredException' => __DIR__ . '/..' . '/firebase/php-jwt/Exceptions/ExpiredException.php',
        'JWT' => __DIR__ . '/..' . '/firebase/php-jwt/Authentication/JWT.php',
        'SignatureInvalidException' => __DIR__ . '/..' . '/firebase/php-jwt/Exceptions/SignatureInvalidException.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit82ae54f036baa84772f44e235d3aa36c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit82ae54f036baa84772f44e235d3aa36c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit82ae54f036baa84772f44e235d3aa36c::$classMap;

        }, null, ClassLoader::class);
    }
}
